version: "3.8"

services:
  frontend:
    image: desk-bookings-frontend:latest
    container_name: frontend
    ports:
      - "7070:8080"
    depends_on:
      - backend
    environment:
      BACKEND_ADDRESS: http://backend:8080

  backend:
    image: desk-bookings-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - wiremock
    environment:
      MONGO_URL: mongodb://mongo:27017
      WIREMOCK_URL: http://wiremock:3000
    links:
      - mongo
      - wiremock

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - "3000:3000"
