services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    container_name: mongo-seed
    environment:
      MONGO_DBNAME: "cicd"
    depends_on:
      - mongodb
    links:
      - mongodb

  backend:
    image: ${BE_IMAGE}
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - mongo-seed
    environment:
      MONGO_URL: mongodb://mongodb:27017
      MONGO_DBNAME: "cicd"
      SENDGRID_HOST: ${SENDGRID_HOST}
    links:
      - mongodb

  frontend:
    image: ${FE_IMAGE}
    container_name: frontend
    ports:
      - "7070:8080"
    depends_on:
      - backend
    environment:
      BACKEND_ADDRESS: http://backend:8080
