services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "6060:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  sendgrid-mock:
    image: ghashange/sendgrid-mock:1.12.0
    container_name: sendgrid-mock
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-sendgrid.rule=Host(`api.sendgrid.com`) && PathPrefix(`/v3`)"
      - "traefik.http.services.api-sendgrid.loadbalancer.server.port=3000"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    container_name: mongo-seed
    environment:
      MONGO_DBNAME: "cicd"
    depends_on:
      - mongodb
    links:
      - mongodb

  backend:
    image: desk-bookings-be:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - sendgrid-mock
      - mongo-seed
      - traefik
    environment:
      MONGO_URL: mongodb://mongodb:27017
      SENDGRID_KEY: "key"
      MONGO_DBNAME: "cicd"
    links:
      - mongodb
      - sendgrid-mock
      - traefik

  frontend:
    image: desk-bookings-fe:latest
    container_name: frontend
    ports:
      - "7070:8080"
    depends_on:
      - backend
    environment:
      BACKEND_ADDRESS: http://backend:8080
