# this stage is run before uat-stage and production stage
# in an acceptance environment.
#
# 1. pass input env var
#
# 2. trigger Release System on this environment
#    Release External System Stubs (this is a placeholder step, no actions at the moment)
#    Checkout System Test Repository
#    Run Smoke Tests
#    Run Acceptance Tests
# 3. Tag the
# todo : when e2e acceptance available, change line 44
name: Acceptance Stage

on:
  schedule:
    - cron: "0 1/2 * * 1-5"
  workflow_dispatch:
   inputs:
     e2e:
       description: "Check to run acceptance on end to end environment"
       type: boolean
       required: true

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      acc_env_fe: ${{ steps.set-env.outputs.acc_env_fe }}
      acc_env_be: ${{ steps.set-env.outputs.acc_env_be }}
      tag: ${{steps.generate-tag.outputs.tag}}
    steps:
      - name: Set environment variables
        id: set-env
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
              echo "Scheduled event detected. Defaulting e2e to false."
              e2e=false
          else
              echo "Using e2e input value."
              e2e=${{ inputs.e2e }}
          fi
          
          if [ "$e2e" == "true" ]; then
              echo "acc_env_fe=${{ vars.EB_ENV_ACCEPTANCE_FE }}" >> "$GITHUB_OUTPUT"
              echo "acc_env_be=${{ vars.EB_ENV_ACCEPTANCE_BE }}" >> "$GITHUB_OUTPUT"
          else
              echo "acc_env_fe=${{ vars.EB_ENV_ACCEPTANCE_FE }}" >> "$GITHUB_OUTPUT"
              echo "acc_env_be=${{ vars.EB_ENV_ACCEPTANCE_BE }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Generate acceptance Tag
        id: generate-tag
        run: |
          DATE=$(date +'%d%m%y')
          TIME=$(date +'%H%M')
          TAG="acc-${DATE}-${TIME}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

  check-image-be:
    needs: set-environment
    uses: ./.github/workflows/check-last-creation.yml
    with:
      image-tag: latest
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-be
      file_name: run_be.txt
    secrets: inherit

  check-image-fe:
    needs:
        - set-environment
        - check-image-be
    uses: ./.github/workflows/check-last-creation.yml
    with:
      image-tag: latest
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-fe
      file_name: run_fe.txt
    secrets: inherit

  condition-check:
    runs-on: ubuntu-latest
    needs:
      - check-image-be
      - check-image-fe
    outputs:
      proceed: ${{ steps.determine.outputs.proceed }} || ${{ steps.determine-fe.outputs.proceed }}
    steps:
      - name: Download run be File
        uses: actions/download-artifact@v4
        with:
          name: run_be.txt
      - name: Determine If Deployment Should Proceed for fe
        id: determine-be
        run: |
          if grep -q "false" run_be.txt; then
            echo "proceed=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "proceed=true" >> $GITHUB_OUTPUT
          fi
      - name: Download run fe File
        uses: actions/download-artifact@v4
        with:
          name: run_fe.txt
      - name: Determine If Deployment Should Proceed for fe
        id: determine-fe
        run: |
          if grep -q "false" run_fe.txt; then
            echo "proceed=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "proceed=true" >> $GITHUB_OUTPUT
          fi
  run-deploy-in-environment:
    needs:
        - set-environment
        - condition-check
    if: needs.condition-check.outputs.proceed == 'true'
    uses: 3T-Operations-Team/desk-bookings-system/.github/workflows/release-stage.yml@main
    secrets: inherit
    with:
      EB_APP_FE: ${{ vars.EB_APP_FE }}
      EB_APP_BE: ${{ vars.EB_APP_BE }}
      EB_ENV_FE: ${{ needs.set-environment.outputs.acc_env_fe }}
      EB_ENV_BE: ${{ needs.set-environment.outputs.acc_env_be }}

  run-smoke-test:
    needs:
      - run-deploy-in-environment
      - set-environment
    uses: ./.github/workflows/smoke-test-on-host.yml
    with:
      EB_ENV: ${{ needs.set-environment.outputs.acc_env_fe }}
      BE_URL: ${{ needs.set-environment.outputs.acc_env_be }}
    secrets: inherit

  run-acceptance-test:
    needs:
      - run-smoke-test
      - set-environment
    uses: ./.github/workflows/acceptance-test-on-host.yml
    with:
      EB_ENV: ${{ needs.set-environment.outputs.acc_env_fe }}
    secrets: inherit

  on-acceptance-success-tag-fe:
    needs:
      - set-environment
      - run-acceptance-test
    uses: ./.github/workflows/update-tag.yml
    with:
      image-tag: latest
      new-tag: ${{needs.set-environment.outputs.tag}}
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-fe
    secrets: inherit

  on-acceptance-success-tag-be:
    needs:
      - run-acceptance-test
      - set-environment
    uses: ./.github/workflows/update-tag.yml
    with:
      image-tag: latest
      new-tag: ${{needs.set-environment.outputs.tag}}
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-be
    secrets: inherit
