name: Run Acceptance Test on this Host
on:
  workflow_call:
    inputs:
      EB_ENV:
        required: true
        type: string
  jobs:
    run-acceptance:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout this
          uses: actions/checkout@v4
          with:
            repository: 3T-Operations-Team/desk-bookings-system-tests
            path: desk-bookings-system-tests

        - name: Cypress run in env
          uses: cypress-io/github-action@v6
          env:
            CYPRESS_host: http://${{ inputs.EB_ENV }}.${{ secrets.AWS_REGION }}.elasticbeanstalk.com
            CYPRESS_TEST_USER_EMAIL: ${{ secrets.CYPRESS_TEST_USER_EMAIL }}
            CYPRESS_TEST_USER_TOKEN: ${{ secrets.CYPRESS_TEST_USER_TOKEN }}
            LIBGL_ALWAYS_SOFTWARE: 1
            tags: @acceptance
          with:
            working-directory: desk-bookings-system-tests

        - name: upload screenshot
          uses: actions/upload-artifact@v3
          if: failure()
          with:
            name: cypress-screenshots
            path: desk-bookings-system-tests/cypress/screenshots

