name: Acceptance Stage

on:
    schedule:
      - cron: "0 1/2 * * 1-5"
    workflow_dispatch:


jobs:
  run-acceptance-environment:
    uses: ./.github/workflows/acceptance.yml
    with:
      e2e: false

  run-e2e-environment:
    needs:
      - run-acceptance-environment
    uses: ./.github/workflows/acceptance.yml
    with:
      e2e: true


