name: Acceptance Stage

on:
    schedule:
      - cron: "0 1/2 * * 1-5"
    workflow_dispatch:


jobs:
  run-acceptance-environment:
    uses: ./.github/workflows/acceptance.yml
    with:
      e2e: false

  run-e2e-environment:
    needs:
      - run-acceptance-environment
    uses: ./.github/workflows/acceptance.yml
    with:
      e2e: true

  tag-update-check:
    runs-on: ubuntu-latest
    needs:
      - run-e2e-environment
      - run-acceptance-environment
    outputs:
      proceed: ${{ steps.determine.outputs.proceed }}
    steps:
      - name: Download skip file
        uses: actions/download-artifact@v4
        with:
          name: skip.txt
      - name: Determine tags are needed
        id: determine
        run: |
          if grep -q "false" skip.txt; then
            echo "proceed=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "proceed=true" >> $GITHUB_OUTPUT
          fi
  on-acceptance-success-tag-fe:
    needs:
      - run-acceptance-environment
      - run-e2e-environment
      - tag-update-check
    if: needs.tag-update-check.outputs.proceed == 'true'
    uses: ./.github/workflows/update-tag.yml
    with:
      image-tag: latest
      new-tag: ${{needs.set-environment.outputs.tag}}
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-fe
    secrets: inherit

  on-acceptance-success-tag-be:
    needs:
      - run-acceptance-environment
      - run-e2e-environment
      - tag-update-check
    if: needs.tag-update-check.outputs.proceed == 'true'
    uses: ./.github/workflows/update-tag.yml
    with:
      image-tag: latest
      new-tag: ${{needs.set-environment.outputs.tag}}
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-be
    secrets: inherit


