name: running acceptance on env

on:
  workflow_call:
    inputs:
      e2e:
        description: "Check to run acceptance on end to end environment"
        type: boolean
        required: true
        default: false

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      acc_env_fe: ${{ steps.set-env.outputs.acc_env_fe }}
      acc_env_be: ${{ steps.set-env.outputs.acc_env_be }}
      tag: ${{steps.generate-tag.outputs.tag}}
    steps:
      - name: Set environment variables
        id: set-env
        run: |
          
          if [ "$e2e" == "true" ]; then
              echo "acc_env_fe=${{ vars.EB_ENV_ACCEPTANCE_FE }}" >> "$GITHUB_OUTPUT"
              echo "acc_env_be=${{ vars.EB_ENV_ACCEPTANCE_BE }}" >> "$GITHUB_OUTPUT"
          else
              echo "acc_env_fe=${{ vars.EB_ENV_ACCEPTANCE_FE }}" >> "$GITHUB_OUTPUT"
              echo "acc_env_be=${{ vars.EB_ENV_ACCEPTANCE_BE }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Generate acceptance Tag
        id: generate-tag
        run: |
          DATE=$(date +'%d%m%y')
          TIME=$(date +'%H%M')
          TAG="acc-${DATE}-${TIME}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

  check-image-be:
    needs: set-environment
    uses: ./.github/workflows/check-last-creation.yml
    with:
      image-tag: latest
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-be
      file_name: run_be
      e2e: ${{inputs.e2e}}
    secrets: inherit

  check-image-fe:
    needs:
      - set-environment
      - check-image-be
    uses: ./.github/workflows/check-last-creation.yml
    with:
      image-tag: latest
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-fe
      file_name: run_fe
      e2e : ${{inputs.e2e}}
    secrets: inherit

  condition-check:
    runs-on: ubuntu-latest
    needs:
      - check-image-be
      - check-image-fe
    outputs:
      proceed-be: ${{ steps.determine.outputs.proceed-be }}
      proceed-fe: ${{ steps.determine.outputs.proceed-fe }}
    steps:
      - name: Set artifact filename based on e2e value
        id: set-filename
        run: |
            if [ "${{ inputs.e2e }}" == "true" ]; then
              echo "artifact_name_be=run_be_e2e.txt" >> $GITHUB_ENV
              echo "artifact_name_fe=run_fe_e2e.txt" >> $GITHUB_ENV
            else
              echo "artifact_name_be=run_be.txt" >> $GITHUB_ENV
              echo "artifact_name_fe=run_fe.txt" >> $GITHUB_ENV
            fi

      - name: Download run BE File
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact_name_be}}

      - name: Download run FE File
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact_name_be}}

      - name: Determine If Deployment Should Proceed for BE
        id: determine-be
        run: |
          if grep -q "false" $GITHUB_ENV.artifact_name_be; then
            echo "proceed-be=false" >> $GITHUB_OUTPUT
            echo "skip-be=true" >> skip.txt
            exit 0
          else
            echo "proceed-be=true" >> $GITHUB_OUTPUT
            echo "skip-be=false" >> skip.txt
          fi
      - name: Determine If Deployment Should Proceed for fe
        id: determine-fe
        run: |
          if grep -q "false" $GITHUB_ENV.artifact_name_fe; then
            echo "proceed-fe=false" >> $GITHUB_OUTPUT
            echo "skip-fe=true" >> skip.txt
            exit 0
          else
            echo "proceed-fe=true" >> $GITHUB_OUTPUT
            echo "skip-fe=false" >> skip.txt
          fi

      - name: Upload File
        uses: actions/upload-artifact@v4
        if: ${{inputs.e2e}} == 'true'
        with:
          name: skip_e2e.txt
          path: skip.txt

      - name: Upload File
        uses: actions/upload-artifact@v4
        if: ${{inputs.e2e}} == 'false'
        with:
          name: skip_acceptance.txt
          path: skip.txt

  run-deploy-in-environment:
    needs:
      - set-environment
      - condition-check
    if: needs.condition-check.outputs.proceed-be == 'true' && needs.condition-check.outputs.proceed-fe == 'true'
    uses: 3T-Operations-Team/desk-bookings-system/.github/workflows/release-stage.yml@main
    secrets: inherit
    with:
      EB_APP_FE: ${{ vars.EB_APP_FE }}
      EB_APP_BE: ${{ vars.EB_APP_BE }}
      EB_ENV_FE: ${{ needs.set-environment.outputs.acc_env_fe }}
      EB_ENV_BE: ${{ needs.set-environment.outputs.acc_env_be }}

  run-smoke-test:
    if: ${{inputs.e2e}} == 'false'
    needs:
      - run-deploy-in-environment
      - set-environment
    uses: ./.github/workflows/smoke-test-on-host.yml
    with:
      EB_ENV: ${{ needs.set-environment.outputs.acc_env_fe }}
      BE_URL: ${{ needs.set-environment.outputs.acc_env_be }}
      SENDGRID_HOST: ${{ vars.SENDGRID_HOST_MOCK }}
    secrets: inherit

  run-acceptance-test:
    if: ${{inputs.e2e}} == 'false'
    needs:
      - run-smoke-test
      - set-environment
    uses: ./.github/workflows/acceptance-test-on-host.yml
    with:
      EB_ENV: ${{ needs.set-environment.outputs.acc_env_fe }}
    secrets: inherit

  run-e2e-test:
    if: ${{inputs.e2e}} == 'true'
    needs:
      - run-smoke-test
      - set-environment
    uses: ./.github/workflows/e2e-test-on-host.yml
    with:
      EB_ENV: ${{ needs.set-environment.outputs.acc_env_fe }}
    secrets: inherit
