name: Acceptance Stage

on:
    schedule:
      - cron: "0 1/2 * * 1-5"
    workflow_dispatch:


jobs:
  run-acceptance-environment:
    uses: ./.github/workflows/acceptance.yml
    with:
      e2e: false

  run-e2e-environment:
    needs:
      - run-acceptance-environment
    uses: ./.github/workflows/acceptance.yml
    with:
      e2e: true

  tag-update-check:
    runs-on: ubuntu-latest
    needs:
      - run-e2e-environment
      - run-acceptance-environment
    outputs:
      tag-fe: ${{ steps.determine.outputs.tag-fe }}
      tag-be: ${{ steps.determine.outputs.tag-be }}
    steps:
      - name: Download skip acceptance file
        uses: actions/download-artifact@v4
        with:
          name: skip_acceptance.txt
      - name: Download skip e2e file
        uses: actions/download-artifact@v4
        with:
          name: skip_e2e.txt
      - name: Determine tags are needed
        id: determine
        run: |
          proceed_fe_acceptance=$(grep -oP '(?<=skip-fe=)[a-zA-Z]+' skip_acceptance.txt)
          proceed_fe_e2e=$(grep -oP '(?<=skip-fe=)[a-zA-Z]+' skip_e2e.txt)
          
          if [[ "$proceed_fe_acceptance" == "false" || "$proceed_fe_e2e" == "false" ]]; then
            echo "tag-fe=false" >> $GITHUB_OUTPUT
          else
            echo "tag-fe=true" >> $GITHUB_OUTPUT
          fi
          
          proceed_be_acceptance=$(grep -oP '(?<=skip-be=)[a-zA-Z]+' skip_acceptance.txt)
          proceed_be_e2e=$(grep -oP '(?<=skip-be=)[a-zA-Z]+' skip_e2e.txt)

          if [[ "$proceed_be_acceptance" == "false" || "$proceed_be_e2e" == "false" ]]; then
            echo "tag-be=false" >> $GITHUB_OUTPUT
          else
            echo "tag-be=true" >> $GITHUB_OUTPUT
          fi
  on-acceptance-success-tag-fe:
    needs:
      - run-acceptance-environment
      - run-e2e-environment
      - tag-update-check
    if: needs.tag-update-check.outputs.tag-fe == 'true'
    uses: ./.github/workflows/update-tag.yml
    with:
      image-tag: latest
      new-tag: ${{needs.set-environment.outputs.tag}}
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-fe
    secrets: inherit

  on-acceptance-success-tag-be:
    needs:
      - run-acceptance-environment
      - run-e2e-environment
      - tag-update-check
    if: needs.tag-update-check.outputs.tag-be == 'true'
    uses: ./.github/workflows/update-tag.yml
    with:
      image-tag: latest
      new-tag: ${{needs.set-environment.outputs.tag}}
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-be
    secrets: inherit


