name: External Contract Tests
on:
  workflow_call:
    inputs:
      EB_ENV:
        required: true
        type: string
jobs:
  run-acceptance:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this
        uses: actions/checkout@v4
        with:
          repository: 3T-Operations-Team/desk-bookings-system-tests

      - name: Cypress run in env
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_HOST: http://${{ inputs.EB_ENV }}.${{ secrets.AWS_REGION }}.elasticbeanstalk.com
          CYPRESS_SENDGRID_STUB: ${{ vars.SENDGRID_HOST_MOCK }}
          CYPRESS_SENDGRID_REAL: ${{ vars.SENDGRID_HOST }}
          LIBGL_ALWAYS_SOFTWARE: 1
        with:
          spec: tests/external-contract/*

      - name: upload screenshot
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
