# production stage deployment workflow after successful
name: Run Production Stage

on:
  #todo : make it a cron job that runs every n hours
  workflow_dispatch:

jobs:
  run-production-deploy:
    uses: ./.github/workflows/release-stage.yml
    secrets: inherit
    with:
      EB_APP_FE: ${{ vars.EB_APP_FE }}
      EB_APP_BE: ${{ vars.EB_APP_BE }}
      EB_ENV_FE: ${{ vars.EB_ENV_PROD_FE }}
      EB_ENV_BE: ${{ vars.EB_ENV_PROD_BE }}
