name: Run UAT stage tests

on:
  workflow_dispatch:

jobs:
  run-smoke-test:
    uses: 3T-Operations-Team/desk-bookings-system-tests/.github/workflows/smoke-test-on-host.yml@main
    with:
      EB_ENV: ${{ vars.EB_UAT_ENV_FE }}
    secrets: inherit
