name: Run Smoke Test on this Host
on:
  workflow_call:
    inputs:
      EB_ENV:
        required: true
        type: string
jobs:
  run-smoke:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this
        uses: actions/checkout@v4
        with:
          repository: 3T-Operations-Team/desk-bookings-system-tests
          path: desk-bookings-system-tests

      - name: Cypress run in env
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_host: http://${{ inputs.EB_ENV }}.${{ secrets.AWS_REGION }}.elasticbeanstalk.com
          CYPRESS_TEST_USER_EMAIL: ${{ secrets.CYPRESS_TEST_USER_EMAIL }}
          CYPRESS_TEST_USER_TOKEN: ${{ secrets.CYPRESS_TEST_USER_TOKEN }}
          LIBGL_ALWAYS_SOFTWARE: 1
        with:
          working-directory: desk-bookings-system-tests

      - name: upload screenshot
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: desk-bookings-system-tests/cypress/screenshots

      - name: Zip results
        if: failure()
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r cypress.zip cypress

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{secrets.MAIL_SERVER}}
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Smoke tests failed - ${{ inputs.EB_ENV }}
          to: ${{secrets.MAIL_SLACK_CHANNEL}}
          from: GitHub Actions
          attachments: ./cypress.zip
