name: Run Acceptance Test on docker compose

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  run-acceptance:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this
        uses: actions/checkout@v4
        with:
          repository: 3T-Operations-Team/desk-bookings-system-tests

      - name: Registry login
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start containers
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
        env:
          SENDGRID_HOST: ${{ vars.SENDGRID_HOST }}

      - name: Run all cypress tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_host: http://localhost:7070
          CYPRESS_be_host: http://localhost:8080
          CYPRESS_TEST_USER_EMAIL: ${{ secrets.CYPRESS_TEST_USER_EMAIL }}
          CYPRESS_TEST_USER_TOKEN: ${{ secrets.CYPRESS_TEST_USER_TOKEN }}
          CYPRESS_TEST_USER_PASSWORD: ${{ secrets.CYPRESS_TEST_USER_PASSWORD }}
          LIBGL_ALWAYS_SOFTWARE: 1

      - name: upload screenshot
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: desk-bookings-system-tests/cypress/screenshots
