# this workflow gets image with "image tag" input and tag it with new-tag.
name: Update tag
on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      new-tag:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Registry login
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Docker Image
        run: |
            docker pull ${{ inputs.IMAGE_NAME }}:${{ inputs.image-tag }}

      - name: Get image id
        id: image_id
        run: |
            IMAGE_ID=$(docker inspect --format='{{.Id}}' ${{ inputs.IMAGE_NAME }}:${{ inputs.image-tag }})
            echo "IMAGE_ID=${IMAGE_ID}" >> $GITHUB_ENV
      - name: Output Image ID
        run: echo "The Docker Image ID is $IMAGE_ID"
      - name : check tags
        run: |
            docker inspect --format='{{json .RepoTags}}' <image-id> | grep -o '"acc-[^"]*"' || echo "No tags starting with acc- found"

#      - name: Tag image with new tag
#        run: |
#            docker tag $IMAGE_ID ${{ inputs.IMAGE_NAME }}:${{ inputs.new-tag }}
#
#      - name: Push New Tag
#        run: |
#            docker push ${{ inputs.IMAGE_NAME }}:${{ inputs.new-tag }}
